version: 2.1

executors:
  podman-executor:
    docker:
      - image: quay.io/podman/stable:latest # Image hỗ trợ Podman
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: podman-executor
    environment:
      REGISTRY_URL: "https://mmregistry.mmvietnam.com:5000"
      IMAGE_NAME: "my-react-app" # Tên image của bạn
    steps:
      - checkout
      - run:
          name: Cài đặt Git và Podman
          command: |
            apt-get update && apt-get install -y git podman
            echo "[registries.insecure]
            registries = ['mmregistry.mmvietnam.com:5000']" > /etc/containers/registries.conf
      - run:
          name: Clone Source Code
          command: |
            git clone https://longthanhdam:${GITHUB_TOKEN}@github.com/longthanhdam/my-react-app.git .
      - run:
          name: Build React App
          command: |
            npm install
            npm run build
      - run:
          name: Build Podman Image
          command: |
            podman build -t ${REGISTRY_URL}/${IMAGE_NAME}:latest .
      - run:
          name: Push Image to Private Registry
          command: |
            podman login ${REGISTRY_URL} --username "infra01" --password "MMprivateauthen"
            podman push ${REGISTRY_URL}/${IMAGE_NAME}:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push

